server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://52.149.226.198:5432/rosatomdb
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: rosatom
    create-schemas: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: true
active-mq:
  broker-url: tcp://52.149.226.198:61616
  topic: demo.topic
  queue: demo.queue
  rosatom:
    tsp-input-queue: rosatom.tsp.input
    tsp-output-queue: rosatom.tsp.output

